(dp1
S'output'
p2
S"<class 'sqlite3.IntegrityError'> foreign key constraint failed"
p3
sS'layer'
p4
S'/home/riarussi/src/plone_creator/web2py/applications/AdminSItes/controllers/default.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n### required - do no delete\ndef user(): return dict(form=auth())\ndef download(): return response.download(request,db)\ndef call(): return service()\n### end requires\ndef index():\n    return dict()\n\ndef error():\n    return dict()\n\n@auth.requires_login()\ndef tbl_components_manage():\n    form = SQLFORM.smartgrid(db.t_tbl_components,onupdate=auth.archive)\n    return locals()\n\ndef tbl_components_read():\n    return dict()\nresponse._vars=response._caller(user)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/riarussi/src/plone_creator/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/riarussi/src/plone_creator/web2py/applications/AdminSItes/controllers/default.py", line 20, in <module>\n  File "/home/riarussi/src/plone_creator/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/riarussi/src/plone_creator/web2py/applications/AdminSItes/controllers/default.py", line 3, in user\n    def user(): return dict(form=auth())\n  File "/home/riarussi/src/plone_creator/web2py/gluon/tools.py", line 1923, in __call__\n    return getattr(self, args[0])()\n  File "/home/riarussi/src/plone_creator/web2py/gluon/tools.py", line 3231, in logout\n    self.log_event(log, self.user)\n  File "/home/riarussi/src/plone_creator/web2py/gluon/tools.py", line 2521, in log_event\n    origin=origin, user_id=user_id)\n  File "/home/riarussi/src/plone_creator/web2py/gluon/packages/dal/pydal/objects.py", line 731, in insert\n    ret = self._db._adapter.insert(self, self._listify(fields))\n  File "/home/riarussi/src/plone_creator/web2py/gluon/packages/dal/pydal/adapters/base.py", line 746, in insert\n    raise e\nIntegrityError: foreign key constraint failed\n'
p11
s.