(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'e' is not defined"
p3
sS'layer'
p4
S'/home/riarussi/src/plone_creator/web2py/applications/AdminSItes/controllers/sites.py'
p5
sS'code'
p6
S'### SITE PLONE\n\ndef add():\n\timport os, sys\n\tif request.post_vars.site:\n\t\tsite = request.post_vars.site\n\t\tpath = str("/home/riarussi/src/sites/")+str(site)\n\t\ttry:\n\t\t\tos.mkdir( path, 0755 );\n\t\texcept e:\n\t\t\traise HTTP(500, T(\'teste\'))\n\telse:\n\t\tsite = None\n\tlista = os.listdir("/home/riarussi/src/sites/")\n\treturn dict(lista=lista,site=site)\nresponse._vars=response._caller(add)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/riarussi/src/plone_creator/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/riarussi/src/plone_creator/web2py/applications/AdminSItes/controllers/sites.py", line 16, in <module>\n  File "/home/riarussi/src/plone_creator/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/riarussi/src/plone_creator/web2py/applications/AdminSItes/controllers/sites.py", line 10, in add\n    except e:\nNameError: global name \'e\' is not defined\n'
p11
s.