(dp1
S'output'
p2
S"<type 'exceptions.OSError'> [Errno 2] No such file or directory: '/sites/'"
p3
sS'layer'
p4
S'/home/riarussi/projetos/Prodam-Gerenciador-de-SItes/web2py/applications/AdminSItes/controllers/sites.py'
p5
sS'code'
p6
S'### SITE PLONE\n@auth.requires_permission(\'default\', \'\')\ndef add():\n\timport os, sys\n\tif request.post_vars.site:\n\t\tsite = request.post_vars.site\n\t\tpath = str("/sites/prodam.gerenciador.")+str(site)\n\t\ttry:\n\t\t\tos.mkdir( path, 0755 );\n\t\t\tpath = str("/sites/prodam.gerenciador.")+str(site)+str(\'/src\')\n\t\t\tos.mkdir( path, 0755 );\n\t\t\tpath = str("/sites/prodam.gerenciador.")+str(site)+str(\'/src/prodam\')\n\t\t\tos.mkdir( path, 0755 );\n\t\t\tpath = str("/sites/prodam.gerenciador.")+str(site)+str(\'/src/prodam/gerenciador\')\n\t\t\tos.mkdir( path, 0755 );\n\t\t\tpath = str("/sites/prodam.gerenciador.")+str(site)+str(\'/src/prodam/gerenciador/\')+str(site)\n\t\t\tos.mkdir( path, 0755 );\n\t\texcept:\n\t\t\traise HTTP(500, T(\'Erro ao criar o diret\xc3\xb3rio\'))\n\telse:\n\t\tsite = None\n\tlista = os.listdir("/sites/")\n\treturn dict(lista=lista,site=site)\n\n\n\n\nresponse._vars=response._caller(add)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/riarussi/projetos/Prodam-Gerenciador-de-SItes/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/riarussi/projetos/Prodam-Gerenciador-de-SItes/web2py/applications/AdminSItes/controllers/sites.py", line 28, in <module>\n  File "/home/riarussi/projetos/Prodam-Gerenciador-de-SItes/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/riarussi/projetos/Prodam-Gerenciador-de-SItes/web2py/gluon/tools.py", line 4236, in f\n    return action(*a, **b)\n  File "/home/riarussi/projetos/Prodam-Gerenciador-de-SItes/web2py/applications/AdminSItes/controllers/sites.py", line 22, in add\n    lista = os.listdir("/sites/")\nOSError: [Errno 2] No such file or directory: \'/sites/\'\n'
p11
s.